spring:
#  neo4j测试地址
  neo4j:
    uri: neo4j://10.30.238.17:7687
    #uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
#  datasource:
##    airflow从库地址，只能用于查询
#    url: jdbc:mysql://bi.datameta.sjhl.mdbm.ziroom.com:3306/zrairflow_new?characterEncoding=utf8&useSSL=false
#    username: zrairflow
#    password: zrairflow
#    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
#    initialization-mode: NEVER